In [1]:
import numpy as np

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [3]:
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [4]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [6]:
torch.manual_seed(1)

# low-level implementation

In [7]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    hypothesis = x_train.matmul(W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} | Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 | Cost: 26811.960938
Epoch    1/20 | Cost: 9920.530273
Epoch    2/20 | Cost: 3675.298828
Epoch    3/20 | Cost: 1366.260986
Epoch    4/20 | Cost: 512.542297
Epoch    5/20 | Cost: 196.896500
Epoch    6/20 | Cost: 80.190903
Epoch    7/20 | Cost: 37.038647
Epoch    8/20 | Cost: 21.081354
Epoch    9/20 | Cost: 15.178741
Epoch   10/20 | Cost: 12.993667
Epoch   11/20 | Cost: 12.183028
Epoch   12/20 | Cost: 11.880545
Epoch   13/20 | Cost: 11.765953
Epoch   14/20 | Cost: 11.720860
Epoch   15/20 | Cost: 11.701425
Epoch   16/20 | Cost: 11.691506
Epoch   17/20 | Cost: 11.685120
Epoch   18/20 | Cost: 11.680006
Epoch   19/20 | Cost: 11.675381
Epoch   20/20 | Cost: 11.670943


# High-level implementation

In [8]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [9]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750000
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219360
Epoch    4/20 Cost: 551.693909
Epoch    5/20 Cost: 213.934662
Epoch    6/20 Cost: 89.052254
Epoch    7/20 Cost: 42.876022
Epoch    8/20 Cost: 25.799620
Epoch    9/20 Cost: 19.482409
Epoch   10/20 Cost: 17.143106
Epoch   11/20 Cost: 16.274515
Epoch   12/20 Cost: 15.949698
Epoch   13/20 Cost: 15.825971
Epoch   14/20 Cost: 15.776586
Epoch   15/20 Cost: 15.754648
Epoch   16/20 Cost: 15.742906
Epoch   17/20 Cost: 15.734898
Epoch   18/20 Cost: 15.728318
Epoch   19/20 Cost: 15.722224
Epoch   20/20 Cost: 15.716328
